name: flutter_ton_buttons
description: "Flutter TON connect buttons"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.0'
  flutter: '>=3.3.0'

dependencies:
  darttonconnect_plus:
    git: https://github.com/aap17/dart_ton_plus.git
  flutter_svg: ^2.0.16
  url_launcher: ^6.3.1

flutter:
  assets:
    - assets/images/ton_icon.svg