name: flutter_ton_buttons
description: "Flutter TON connect buttons"
version: 1.0.0
homepage: https://github.com/aap17/flutter_ton_buttons

environment:
  sdk: '>=3.3.0'
  flutter: '>=3.3.0'

dependencies:
  darttonconnect_plus: ^1.0.1
  flutter_svg: ^2.0.16
  url_launcher: ^6.3.1
  material: ^1.0.0

flutter:
  assets:
    - assets/images/ton_icon.svg